---
- hosts: centos
  become: true
  roles:
    - packages
  tags: [ "packages" ]

- hosts: centos
  become: true
  roles:
    - mysql57
  tags: [ "mysql57" ] 

- hosts: centos       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: msingh         # Update username for remote server
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - tomcat
  tags: [ "tomcat" ]     

- hosts: centos
  become: true
  roles:
    - repo
  tags: [ "repo" ]

- hosts: centos
  gather_facts: yes
  roles:
    - redis
  tags: [ "redis" ]
  become: true
- hosts: centos
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - nodejs
  tags: [ "nodejs" ]
  become: true
